version: "3.7"
services:
    app:
        build:
            args:
                user: dev
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: ordenai-laravel
        container_name: ordenai-backend-laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network
    db:
        image: mysql:8.0
        container_name: ordenai-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ordenai
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - app-network
    nginx:
        image: nginx:alpine
        container_name: ordenai-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - app-network
networks:
    app-network:
      driver: bridge
